In [34]:
import pandas as pd
data = pd.read_csv(r'./data/America.csv', index_col=0, parse_dates=True, dtype=object)
data = data.loc[data["code"].isin(["AAPL","ADBE","BABA","SNE","V"])]
features = ["close","high","low","open"]
data[features] = data[features].astype(float)
data

             close    open    high     low   volume percent  code
time
2015-01-05  106.25  108.29  108.65  105.41   64.29M  -2.82%  AAPL
2015-01-06  106.26  106.54  107.43  104.63   65.80M   0.01%  AAPL
2015-01-07  107.75  107.20  108.20  106.69   40.11M   1.40%  AAPL
2015-01-08  111.89  109.23  112.15  108.70   59.36M   3.84%  AAPL
2015-01-09  112.01  112.67  113.25  110.21   53.70M   0.11%  AAPL
...            ...     ...     ...     ...      ...     ...   ...
2017-12-22   45.68   45.73   45.78   45.44  453.37K   0.59%   SNE
2017-12-26   45.21   45.34   45.46   45.13  584.26K  -1.03%   SNE
2017-12-27   45.26   45.20   45.27   45.07  386.53K   0.11%   SNE
2017-12-28   45.29   45.30   45.42   45.17  541.48K   0.07%   SNE
2017-12-29   44.95   45.29   45.29   44.95  435.67K  -0.75%   SNE

[3772 rows x 7 columns]

In [35]:
start_date = "2015-01-05"
end_date = "2016-12-31"
mask = (data.index >= start_date) & (data.index <= end_date)
data = data[mask]
data

             close    open    high     low   volume percent  code
time
2015-01-05  106.25  108.29  108.65  105.41   64.29M  -2.82%  AAPL
2015-01-06  106.26  106.54  107.43  104.63   65.80M   0.01%  AAPL
2015-01-07  107.75  107.20  108.20  106.69   40.11M   1.40%  AAPL
2015-01-08  111.89  109.23  112.15  108.70   59.36M   3.84%  AAPL
2015-01-09  112.01  112.67  113.25  110.21   53.70M   0.11%  AAPL
...            ...     ...     ...     ...      ...     ...   ...
2016-12-23   28.46   28.36   28.49   28.36  331.43K   0.39%   SNE
2016-12-27   28.38   28.30   28.48   28.29  402.47K  -0.28%   SNE
2016-12-28   28.28   28.50   28.50   28.27  355.88K  -0.35%   SNE
2016-12-29   28.15   28.18   28.26   28.12  431.47K  -0.46%   SNE
2016-12-30   28.03   28.00   28.12   27.91  645.36K  -0.43%   SNE

[2517 rows x 7 columns]

In [36]:
asset_dict = dict()
date_len = len(data.index.unique())
date_len # 日期长度

504

In [37]:
pd.set_option('future.no_silent_downcasting', True) # 设置Pandas选项来禁用静默向下转换，解决填充警告
for asset in ["AAPL","ADBE","BABA","SNE","V"]:
    asset_data = data[data["code"] == asset].reindex(data.index.unique()).sort_index()
    # asset_data['close'] = asset_data['close'].fillna(method='pad')
    
    # 预处理（填充缺失数据、删除code列）
    asset_data = asset_data.bfill(axis=1)  # 后向填充
    asset_data = asset_data.ffill(axis=1)  # 前向填充
    
    # 归一化（最后一天收盘价为基准）
    base_price = asset_data['close'].iloc[-1]
    asset_data['close'] = asset_data['close'] / base_price
    asset_data['high'] = asset_data['high'] / base_price
    asset_data['low'] = asset_data['low'] / base_price
    asset_data['open'] = asset_data['open'] / base_price
    # 以字典形式保存处理好的数据
    asset_dict[str(asset)] = asset_data
    
asset_dict

{'AAPL':                close      open      high       low  volume percent  code
 time
 2015-01-05  0.917372  0.934985  0.938094  0.910119  64.29M  -2.82%  AAPL
 2015-01-06  0.917458  0.919876   0.92756  0.903385  65.80M   0.01%  AAPL
 2015-01-07  0.930323  0.925574  0.934208  0.921171  40.11M   1.40%  AAPL
 2015-01-08  0.966068  0.943101  0.968313  0.938525  59.36M   3.84%  AAPL
 2015-01-09  0.967104  0.972803   0.97781  0.951563  53.70M   0.11%  AAPL
 ...              ...       ...       ...       ...     ...     ...   ...
 2016-12-23  1.006044  0.998014  1.006044  0.998014  14.25M   0.20%  AAPL
 2016-12-27  1.012433  1.006044  1.017095  1.005785  18.30M   0.64%  AAPL
 2016-12-28  1.008116  1.014678  1.018995  1.003281  20.91M  -0.43%  AAPL
 2016-12-29  1.007857  1.005439  1.011138  1.005008  15.04M  -0.03%  AAPL
 2016-12-30       1.0  1.007166  1.011915  0.996633  30.59M  -0.78%  AAPL

 [504 rows x 7 columns],
 'ADBE':                close      open      high       low volume percent  code
 time
 2015-01-05  0.699174  0.701408  0.703545  0.695192  2.41M  -0.50%  ADBE
 2015-01-06   0.68509  0.698883   0.70034  0.678776  2.90M  -2.01%  ADBE
 2015-01-07  0.690724  0.687421  0.692472  0.684021  2.38M   0.82%  ADBE
 2015-01-08  0.708305  0.693541  0.709665  0.692666  2.62M   2.55%  ADBE
 2015-01-09  0.697814  0.708014  0.710345  0.695775  1.73M  -1.48%  ADBE
 ...              ...       ...       ...       ...    ...     ...   ...
 2016-12-23  1.020107  1.016124  1.023992  1.016124  1.05M   0.29%  ADBE
 2016-12-27  1.019718  1.019913  1.028655  1.018553  1.05M  -0.04%  ADBE
 2016-12-28  1.007965  1.018261  1.021467  1.005342  1.74M  -1.15%  ADBE
 2016-12-29  1.007091  1.006605  1.013987  1.004468  1.09M  -0.09%  ADBE
 2016-12-30       1.0  1.010879  1.012336  0.995338  2.10M  -0.70%  ADBE

 [504 rows x 7 columns],
 'BABA':                close      open      high       low  volume percent  code
 time
 2015-01-05  1.150211  1.170254  1.173215  1.137684  18.34M  -2.51%  BABA
 2015-01-06  1.176631  1.153058  1.182667  1.140075  15.72M   2.30%  BABA
 2015-01-07  1.163079  1.191094  1.192803  1.161941  11.05M  -1.15%  BABA
 2015-01-08  1.196105  1.172418  1.199636  1.169343  12.94M   2.84%  BABA
 2015-01-09  1.173215  1.198497   1.19918  1.171734  10.22M  -1.91%  BABA
 ...              ...       ...       ...       ...     ...     ...   ...
 2016-12-23  0.988384  0.986448   0.99852  0.986448   6.36M  -0.01%  BABA
 2016-12-27  0.996925  0.987587   1.00148  0.987473   5.23M   0.86%  BABA
 2016-12-28  0.994989   1.00558  1.010705  0.993281   6.42M  -0.19%  BABA
 2016-12-29  0.994534  1.000114  1.004441  0.992598   5.47M  -0.05%  BABA
 2016-12-30       1.0  0.997267  1.003303  0.993053   7.21M   0.55%  BABA

 [504 rows x 7 columns],
 'SNE':                close      open      high       low   volume percent code
 time
 2015-01-05  0.722797  0.729575  0.729575  0.721013    1.08M  -1.46%  SNE
 2015-01-06   0.72244  0.729932  0.734213  0.718873    2.21M  -0.05%  SNE
 2015-01-07  0.768106  0.770246  0.774171  0.765965    2.49M   6.32%  SNE
 2015-01-08  0.769176  0.768106  0.771316  0.765965    1.30M   0.14%  SNE
 2015-01-09  0.761327  0.777025  0.777381  0.760614    3.01M  -1.02%  SNE
 ...              ...       ...       ...       ...      ...     ...  ...
 2016-12-23  1.015341  1.011773  1.016411  1.011773  331.43K   0.39%  SNE
 2016-12-27  1.012487  1.009633  1.016054  1.009276  402.47K  -0.28%  SNE
 2016-12-28  1.008919  1.016768  1.016768  1.008562  355.88K  -0.35%  SNE
 2016-12-29  1.004281  1.005351  1.008205  1.003211  431.47K  -0.46%  SNE
 2016-12-30       1.0   0.99893  1.003211  0.995719  645.36K  -0.43%  SNE

 [504 rows x 7 columns],
 'V':                close      open      high       low  volume percent code
 time
 2015-01-05  0.830428  0.844271  0.844271  0.829531  12.75M  -2.20%    V
 2015-01-06  0.825173  0.832479  0.835555  0.816585  11.07M  -0.63%    V
 2015-01-07  0.836196  0.828121  0.836709  0.824917   9.35M   1.34%    V
 2015-01-08  0.847347  0.843373  0.849526  0.841579  10.44M   1.33%    V
 2015-01-09  0.834786  0.844655  0.847475  0.832351  10.52M  -1.48%    V
 ...              ...       ...       ...       ...     ...     ...  ...
 2016-12-23  1.001666  1.000769  1.005896  0.998462   6.19M   0.32%    V
 2016-12-27   1.00423  1.003204  1.010638  1.002692   3.78M   0.26%    V
 2016-12-28  1.003589  1.004871  1.008075  0.999359   7.59M  -0.06%    V
 2016-12-29  1.003973  1.006024   1.01051  1.003589   6.24M   0.04%    V
 2016-12-30       1.0  1.005255  1.006665  0.998975   7.13M  -0.40%    V

 [504 rows x 7 columns]}

In [64]:
import numpy as np
states = []  # 存储所有状态张量的列表
y0=np.array([[1],[1],[1],[1],[1],[1]])
price_history = [y0]  # 存储价格历史用于计算回报的列表
t = 1 # 时刻指针
M = 6 # 股票数
L = 1 # 时间窗口长度
N = 4 # CHLO特征数

In [65]:
while t <= date_len: # 【1~504】
    # 初始化各个特征矩阵，第一行是现金资产（值始终为1）
    V_close = np.ones(L)  # 收盘价特征矩阵，现金资产始终为1
    V_high = np.ones(L)   # 最高价矩阵
    V_open = np.ones(L)  # 开盘价矩阵
    V_low = np.ones(L)  # 最低价矩阵
    y = np.ones(1)  # 收盘价涨幅变化
    
    for asset in  ["AAPL","ADBE","BABA","SNE","V"]:
        asset_data = asset_dict[str(asset)]  # 获取该资产的数据

        # 堆叠各个特征的历史数据
        # np.vstack() - 垂直堆叠数组
        # asset_data.iloc[t - self.L - 1:t - 1] - 获取从t-L-1到t-1的历史数据【窗口为1也可以直接取值】
        V_close = np.vstack((V_close, asset_data.iloc[t - L :t ]['close'].values))
        V_high = np.vstack((V_high, asset_data.iloc[t - L :t ]['high'].values))
        V_low = np.vstack((V_low, asset_data.iloc[t - L :t ]['low'].values))
        V_open = np.vstack((V_open, asset_data.iloc[t - L :t ]['open'].values))
        if t != 1:
            y = np.vstack((y, asset_data.iloc[t-1]['close'] / asset_data.iloc[t-2]['close']))
    state = V_close
    # np.stack() - 沿着新轴堆叠数组，axis=2表示在第三个维度堆叠【特征】
    state = np.stack((state, V_high, V_low, V_open), axis=2)
    state = state.reshape(1, M, L, N)
    states.append(state)  # 保存状态到列表
    if t != 1:
        price_history.append(y)  # 保存价格变化到列表
    t = t + 1  # 移动到下一个时间点
# 重置环境，开始训练
t=1
START_FLAG = True

In [66]:
# state
# state = [
#     # 资产0：现金
#     [[1.0, 1.0, 1.0, 1.0]],  # [收盘价, 最高价, 最低价, 开盘价]
    
#     # 资产1：AAPL  
#     [[1.02, 1.05, 0.98, 1.01]],
    
#     # 资产2：ADBE
#     [[0.98, 1.00, 0.95, 0.99]],
    
#     # 资产3：BABA
#     [[1.05, 1.08, 1.02, 1.06]],
    
#     # 资产4：SNE
#     [[0.99, 1.01, 0.97, 1.00]],
    
#     # 资产5：V
#     [[1.01, 1.03, 0.99, 1.02]]
# ]
len(states),states

(504,
 [array([[[[1.0, 1.0, 1.0, 1.0]],

          [[0.9173717838024521, 0.9380935935071664, 0.9101191504058022,
            0.9349853220514592]],

          [[0.6991743564837299, 0.7035454103933949, 0.6951918406993686,
            0.7014084507042253]],

          [[1.150210682154652, 1.173214895797745, 1.1376836351212847,
            1.1702539574080402]],

          [[0.7227970032108455, 0.7295754548697824, 0.7210132001427042,
            0.7295754548697824]],

          [[0.8304280953601642, 0.8442706998205589, 0.8295308895155089,
            0.8442706998205589]]]], dtype=object),
  array([[[[1.0, 1.0, 1.0, 1.0]],

          [[0.9174581246762218, 0.92756000690727, 0.90338456225177,
            0.9198756691417718]],

          [[0.6850898494414764, 0.7003399708596405, 0.6787761049052937,
            0.6988829528897523]],

          [[1.1766313631704817, 1.1826671221956495, 1.1400751622822,
            1.1530577382985991]],

          [[0.7224402425972173, 0.7342133428469496, 0.7188726364609346,
            0.7299322154834106]],

          [[0.8251730325557549, 0.835554985901051, 0.8165854908997694,
            0.8324788515765189]]]], dtype=object),
  array([[[[1.0, 1.0, 1.0, 1.0]],

          [[0.9303229148678985, 0.9342082541875325, 0.9211707822483164,
            0.9255741668105683]],

          [[0.6907236522583778, 0.6924720738222438, 0.6840213695968916,
            0.6874210781932977]],

          [[1.163079375925293, 1.1928026420681015, 1.1619405534677143,
            1.1910944083817332]],

          [[0.768105601141634, 0.7741705315733143, 0.7659650374598643,
            0.7702461648234035]],

          [[0.8361958472186619, 0.8367085362727507, 0.8249166880287107,
            0.8281209946167649]]]], dtype=object),
  array([[[[1.0, 1.0, 1.0, 1.0]],

          [[0.9660680366085306, 0.9683128993265413, 0.9385252978760146,
            0.9431013641858057]],

          [[0.7083050024283633, 0.7096648858669257, 0.6926663428848956,
            0.6935405536668285]],

          [[1.1961052271950803, 1.1996355768135747, 1.169342899441977,
            1.17241772007744]],

          [[0.7691758829825186, 0.7713164466642882, 0.7659650374598643,
            0.768105601141634]],

          [[0.847346834145091, 0.849525762624968, 0.8415790822865932,
            0.8433734939759037]]]], dtype=object),
  array([[[[1.0, 1.0, 1.0, 1.0]],

          [[0.9671041270937663, 0.977810395441202, 0.9515627698152306,
            0.9728026247625626]],

          [[0.6978144730451675, 0.7103448275862069, 0.6957746478873239,
            0.7080135988343856]],

          [[1.173214895797745, 1.1991800478305432, 1.1717344266028926,
            1.198496754355996]],

          [[0.7613271494826971, 0.7773813770959686, 0.7606136282554405,
            0.7770246164823403]],

          [[0.8347859523199179, 0.8474750064086133, 0.8323506793129967,
            0.8446552166111254]]]], dtype=object),
  array([[[[1.0, 1.0, 1.0, 1.0]],

          [[0.9432740459333449, 0.972457261267484, 0.939388706613711,
            0.9721982386461752]],

          [[0.6908207867897037, 0.7018941233608548, 0.6872268091306459,
            0.7006313744536182]],

          [[1.157271381391641, 1.1770868921535131, 1.1526022093155677,
            1.175264776221387]],

          [[0.7620406707099535, 0.7641812343917231, 0.7574027827327863,
            0.7627541919372101]],

          [[0.8331197128941298, 0.8395283260702384, 0.8302999230966419,
            0.8364521917457063]]]], dtype=object),
  array([[[[1.0, 1.0, 1.0, 1.0]],

          [[0.9516491106890003, 0.973925056121568, 0.940338456225177,
            0.962096356415127]],

          [[0.6856726566294318, 0.7086935405536667, 0.679456046624575,
            0.6988829528897523]],

          [[1.1475913905022206, 1.171278897619861, 1.1389363398246213,
            1.168317959230156]],

          [[0.755618979664645, 0.7666785586871209, 0.7484837673920799,
            0.7634677131644666]],

          [[0.835554985901051, 0.851704691104845, 0.8302999230966419,
            0.8395283260702384]]]], dtype=object),
  array([[[[1.0, 1.0, 1.0, 1.0]],

          [[0.9480227939906752, 0.9539803142807806, 0.9367984804006217,
            0.9414608875841824]],

          [[0.6798445847498785, 0.68382710053424, 0.6700339970859641,
            0.6787761049052937]],

          [[1.1340394032570322, 1.1408723380025054, 1.1167293019018334,
            1.1306229358842956]],

          [[0.7384944702104888, 0.741705315733143, 0.7320727791651801,
            0.7406350338922583]],

          [[0.8188925916431685, 0.8286336836708538, 0.8142783901563703,
            0.8223532427582672]]]], dtype=object),
  array([[[[1.0, 1.0, 1.0, 1.0]],

          [[0.9222932136073217, 0.950267656708686, 0.9209117596270074,
            0.9497496114660681]],

          [[0.6827586206896552, 0.6969402622632346, 0.6814958717824185,
            0.696551724137931]],

          [[1.0967999088942033, 1.1404168090194737, 1.0934973237672245,
            1.1350643434688532]],

          [[0.7466999643239386, 0.7584730645736711, 0.7456296824830538,
            0.7577595433464145]],

          [[0.8110740835683159, 0.8250448602922329, 0.8086388105613946,
            0.8226095872853116]]]], dtype=object),
  array([[[[1.0, 1.0, 1.0, 1.0]],

          [[0.9151269210844414, 0.9288551200138145, 0.9083059920566396,
            0.9241063719564843]],

          [[0.6967459932005828, 0.6979116075764934, 0.6802331228751821,
            0.6802331228751821]],

          [[1.1034050791481609, 1.1137683635121285, 1.0878032114793303,
            1.0942944994875299]],

          [[0.737424188369604, 0.7381377095968605, 0.7256510881198716,
            0.7277916518016411]],

          [[0.8169700076903359, 0.8173545244809024, 0.8059471930274289,
            0.8072289156626506]]]], dtype=object),
  array([[[[1.0, 1.0, 1.0, 1.0]],

          [[0.9386979796235538, 0.9399930927300986, 0.9195303056466932,
            0.9310999827318254]],

          [[0.6944147644487615, 0.6992714910150558, 0.6855755220981058,
            0.6973288003885382]],

          [[1.139277986561895, 1.1412139847397789, 1.1113768363512129,
            1.1194624758000227]],

          [[0.7427755975740278, 0.7463432037103104, 0.7370674277559757,
            0.745986443096682]],

          [[0.8229941040758779, 0.8320943347859524, 0.8146629069469368,
            0.8210715201230454]]]], dtype=object),
  array([[[[1.0, 1.0, 1.0, 1.0]],

          [[0.9458642721464342, 0.9589017440856502, 0.9348126403039199,
            0.9406838197202556]],

          [[0.694900437105391, 0.698300145701797, 0.6835356969402623,
            0.6912093249150072]],

          [[1.176289716433208, 1.1827810044414075, 1.1424666894431157,
            1.147363626010705]],

          [[0.7816625044595077, 0.7887977167320728, 0.7770246164823403,
            0.7798787013913664]],

          [[0.8244039989746218, 0.8319661625224302, 0.8154319405280698,
            0.8208151755960011]]]], dtype=object),
  array([[[[1.0, 1.0, 1.0, 1.0]],

          [[0.9704714211707823, 0.9710758072871698, 0.9473320670005181,
            0.9519944741840789]],

          [[0.7137445361826129, 0.715395823215153, 0.6886838271005343,
            0.6983972802331229]],

          [[1.184375355882018, 1.1948525224917435, 1.174125953763808,
            1.191208290627491]],

          [[0.7909382804138423, 0.7930788440956118, 0.7838030681412771,
            0.7845165893685336]],

          [[0.8254293770827994, 0.8299154063060754, 0.8118431171494489,
            0.8185080748526019]]]], dtype=object),
  array([[[[1.0, 1.0, 1.0, 1.0]],

          [[0.9754791918494216, 0.982127439129684, 0.9629597651528234,
            0.9696080124330858]],

          [[0.7193783389995143, 0.7226809130645945, 0.7096648858669257,
            0.7133559980573093]],

          [[1.174239836009566, 1.1980412253729644, 1.173214895797745,
            1.1846031203735337]],

          [[0.8062789867998573, 0.8162682839814484, 0.7998572957545488,
            0.803068141277203]],

          [[0.8276083055626762, 0.8351704691104845, 0.8273519610356319,
            0.8283773391438093]]]], dtype=object),
  array([[[[1.0, 1.0, 1.0, 1.0]],

          [[0.9765152823346572, 0.9873942324296322, 0.973925056121568,
            0.9820410982559143]],

          [[0.7065565808644972, 0.7105390966488587, 0.6962603205439534,
            0.7052938319572608]],

          [[1.18426147363626, 1.197244049652659, 1.1767452454162395,
            1.1889306457123334]],

          [[0.833749554049233, 0.8373171601855155, 0.8305387085265786,
            0.8312522297538352]],

          [[0.8219687259677005, 0.8244039989746218, 0.8132530120481929,
            0.8232504486029224]]]], dtype=object),
  array([[[[1.0, 1.0, 1.0, 1.0]],

          [[0.9423242963218789, 0.9711621481609395, 0.9413745467104128,
            0.9706441029183216]],

          [[0.6941233608547838, 0.7028654686741136, 0.6902379796017484,
            0.696551724137931]],

          [[1.172303837831682, 1.1794784193144288, 1.1454276278328208,
            1.1717344266028926]],

          [[0.822689975026757, 0.8262575811630396, 0.818408847663218,
            0.8205494113449875]],

          [[0.8042809536016406, 0.8132530120481929, 0.7965906177903102,
            0.8132530120481929]]]], dtype=object),
  array([[[[1.0, 1.0, 1.0, 1.0]],

          [[0.9955966154377484, 1.019858400967018, 0.9955966154377484,
            1.0155413572785357]],

          [[0.6823700825643516, 0.6978144730451675, 0.6806216610004856,
            0.694900437105391]],

          [[1.121170709486391, 1.1557909121967884, 1.1136544812663707,
            1.1422389249516]],

          [[0.8369603995718873, 0.8530146271851587, 0.8362468783446307,
            0.8523011059579022]],

          [[0.7894129710330685, 0.8106895667777493, 0.7892847987695463,
            0.8091514996154833]]]], dtype=object),
  array([[[[1.0, 1.0, 1.0, 1.0]],

          [[1.02659298912105, 1.0290968744603697, 0.9977551372819894,
            1.004317043688482]],

          [[0.6958717824186498, 0.6976202039825157, 0.677804759592035,
            0.6802331228751821]],

          [[1.0227764491515772, 1.0333674980070606, 0.9948752989408951,
            1.030975970846145]],

          [[0.8408847663217981, 0.8419550481626829, 0.8344630752764894,
            0.8405280057081698]],

          [[0.7946680338374776, 0.7972314791079211, 0.7855678031274033,
            0.7931299666752115]]]], dtype=object),
  array([[[[1.0, 1.0, 1.0, 1.0]],

          [[1.0115696770851321, 1.0360904852357107, 1.0088931099982732,
            1.0222759454325678]],

          [[0.6812044681884409, 0.6961631860126275, 0.6805245264691598,
            0.6927634774162214]],

          [[1.0144630452112515, 1.0477166609725543, 1.0034164673727366,
            1.0203849219906616]],

          [[0.8308954691402068, 0.8419550481626829, 0.8301819479129504,
            0.8355333571173743]],

          [[0.8168418354268137, 0.8446552166111254, 0.8168418354268137,
            0.8344014355293514]]]], dtype=object),
  array([[[[1.0, 1.0, 1.0, 1.0]],

          [[1.0242617855292695, 1.0289241927128303, 1.0022448627180107,
            1.0192540148506304]],

          [[0.6907236522583778, 0.6915978630403108, 0.6706168042739195,
            0.6842156386595434]],

          [[1.0264206810158296, 1.0438446646167863, 1.0091105796606308,
            1.0378089055916182]],

          [[0.8323225115947198, 0.833749554049233, 0.8173385658223332,
            0.8191223688904745]],

          [[0.8182517303255576, 0.8213278646500898, 0.8000512689054089,
            0.8213278646500898]]]], dtype=object),
  array([[[[1.0, 1.0, 1.0, 1.0]],

          [[1.0244344672768089, 1.0282334657226733, 1.015455016404766,
            1.0231393541702642]],

          [[0.6985915492957746, 0.6990772219524041, 0.689655172413793,
            0.694900437105391]],

          [[1.0318870288122082, 1.0437307823710285, 1.0238013893633984,
            1.0437307823710285]],

          [[0.8344630752764894, 0.8348198358901177, 0.8255440599357831,
            0.8259008205494113]],

          [[0.8324788515765189, 0.8345296077928737, 0.8163291463727249,
            0.8226095872853116]]]], dtype=object),
  array([[[[1.0, 1.0, 1.0, 1.0]],

          [[1.0322914867898465, 1.0404938697979624, 1.021498877568641,
            1.0231393541702642]],

          [[0.7020883924235065, 0.7053909664885867, 0.6972316658572122,
            0.6973288003885382]],

          [[1.0249402118209772, 1.0463500740234597, 1.0190183350415671,
            1.0362145541510077]],

          [[0.9254370317516947, 0.9471994291830181, 0.8769175882982517,
            0.8876204067070995]],

          [[0.8487567290438349, 0.854652653165855, 0.8302999230966419,
            0.831837990258908]]]], dtype=object),
  array([[[[1.0, 1.0, 1.0, 1.0]],

          [[1.0355724399930928, 1.0380763253324126, 1.0296149197029874,
            1.0362631669832498]],

          [[0.7100534239922291, 0.7108305002428363, 0.70247693054881,
            0.7039339485186984]],

          [[0.9907755380936112, 1.0231180958888508, 0.9805261359754014,
            1.020157157499146]],

          [[0.9568319657509811, 0.9625401355690332, 0.9454156261148768,
            0.9471994291830181]],

          [[0.870930530633171, 0.870930530633171, 0.8519610356318893,
            0.8563188925916433]]]], dtype=object),
  array([[[[1.0, 1.0, 1.0, 1.0]],

          [[1.026852011742359, 1.0382490070799517, 1.022707649801416,
            1.0362631669832498]],

          [[0.7046138902379796, 0.7151044196211753, 0.7016998542982029,
            0.7108305002428363]],

          [[0.9757430816535703, 0.9953308279239267, 0.9727821432638651,
            0.9920282427969479]],

          [[0.9479129504102747, 0.9561184445237245, 0.9461291473421334,
            0.9493399928647877]],

          [[0.856959753909254, 0.8729812868495258, 0.852473724685978,
            0.8708023583696488]]]], dtype=object),
  array([[[[1.0, 1.0, 1.0, 1.0]],

          [[1.0336729407701606, 1.0347090312553964, 1.022534968053877,
            1.0235710585391125]],

          [[0.702574065080136, 0.7088878096163186, 0.6997571636716853,
            0.7002428363283147]],

          [[0.9793873135178226, 0.987928481949664, 0.9733515544926545,
            0.9774513153399385]],

          [[0.9165180164109883, 0.9222261862290403, 0.9147342133428469,
            0.9165180164109883]],

          [[0.8505511407331454, 0.8597795437067419, 0.8500384516790566,
            0.8568315816457318]]]], dtype=object),
  array([[[[1.0, 1.0, 1.0, 1.0]],

          [[1.0535313417371783, 1.0546537730961838, 1.037471939216025,
            1.0375582800897947]],

          [[0.7067508499271491, 0.7109276347741622, 0.7004371053909665,
            0.708499271491015]],

          [[0.9937364764833163, 0.9961280036442318, 0.9853091902972326,
            0.9908894203393691]],

          [[0.9297181591152336, 0.9322154834106314, 0.9193721013200142,
            0.9240099892971815]],

          [[0.8477313509356575, 0.8583696488079979, 0.8447833888746475,
            0.8547808254293771]]]], dtype=object),
  array([[[[1.0, 1.0, 1.0, 1.0]],

          [[1.0782248316352963, 1.0785701951303748, 1.0576757036781212,
            1.0600069072699017]],

          [[0.7091792132102963, 0.7104419621175327, 0.7027683341427877,
            0.7069451189898008]],

          [[0.9793873135178226, 0.9987472952966633, 0.9773374330941805,
            0.9973807083475685]],

          [[0.9311452015697467, 0.9332857652515162, 0.9236532286835534,
            0.9236532286835534]],

          [[0.8523455524224558, 0.8533709305306332, 0.8467059728274802,
            0.8491412458344014]]]], dtype=object),
  array([[[[1.0, 1.0, 1.0, 1.0]],

          [[1.0918666896908997, 1.1006734588154032, 1.0841823519254015,
            1.088413054740114]],

          [[0.7245264691597864, 0.7260806216610005, 0.7120932491500729,
            0.7149101505585235]],

          [[0.99191436055119, 1.0055802300421364, 0.9742626124587176,
            0.974832023687507]],

          [[0.9671780235462004, 0.9682483053870853, 0.9514805565465573,
            0.9518373171601855]],

          [[0.8681107408356833, 0.8681107408356833, 0.8558062035375544,
            0.8576006152268649]]]], dtype=object),
  array([[[[1.0, 1.0, 1.0, 1.0]],

          [[1.0972198238646176, 1.0989466413400104, 1.0848730789155587,
            1.0989466413400104]],

          [[0.7431762991743565, 0.7442447790189413, 0.7262748907236521,
            0.7283147158814959]],

          [[1.0141213984739779, 1.016968454617925, 0.9981778840678739,
            1.0044414075845576]],

          [[0.9739564752051373, 0.9796646450231894, 0.9703888690688547,
            0.970745629682483]],

          [[0.8640092284029736, 0.8740066649577032, 0.8611894386054858,
            0.8740066649577032]]]], dtype=object),
  array([[[[1.0, 1.0, 1.0, 1.0]],

          [[1.1036953893973407, 1.1127611811431533, 1.0958383698843033,
            1.100759799689173]],

          [[0.7491986401165613, 0.7500728508984944, 0.7412336085478387,
            0.7447304516755706]],

          [[0.9890673044072428, 1.0134381049994305, 0.9873590707208746,
            1.011046577838515]],

          [[0.9489832322511594, 0.951123795932929, 0.9382804138423118,
            0.9411344987513378]],

          [[0.867982568572161, 0.8715713919507819, 0.8647782619841067,
            0.8699051525249937]]]], dtype=object),
  array([[[[1.0, 1.0, 1.0, 1.0]],

          [[1.111379727162839, 1.1118977724054568, 1.1004144361940944,
            1.1018822310481784]],

          [[0.7550267119961146, 0.7576493443419136, 0.7459932005828072,
            0.7481301602719767]],

          [[0.9878145997039061, 0.9956724746612003, 0.9850814258057169,
            0.99191436055119]],

          [[0.9996432393863717, 1.0032108455226543, 0.9593292900463789,
            0.9636104174099179]],

          [[0.8623429889771854, 0.8683670853627276, 0.8592668546526533,
            0.867982568572161]]]], dtype=object),
  array([[[[1.0, 1.0, 1.0, 1.0]],

          [[1.1090485235710585, 1.1140562942496979, 1.108012433085823,
            1.1093075461923674]],

          [[0.7550267119961146, 0.7570665371539582, 0.7498785818358427,
            0.7520155415250122]],

          [[0.9895228333902745, 1.0006832934745473, 0.9874729529666324,
            0.9886117754242114]],

          [[0.9764537995005351, 0.9807349268640742, 0.9686050660007134,
            0.9725294327506243]],

          [[0.8623429889771854, 0.8654191233017176, 0.8587541655985645,
            0.8654191233017176]]]], dtype=object),
  array([[[[1.0, 1.0, 1.0, 1.0]],

          [[1.118114315316871, 1.118114315316871, 1.105594888620273,
            1.1105163184251425]],

          [[0.7629917435648372, 0.7630888780961632, 0.7498785818358427,
            0.7553181155900923]],

          [[0.9866757772463273, 0.99407812322059, 0.9837148388566221,
            0.9936225942375584]],

          [[0.9725294327506243, 0.9743132358187655, 0.9593292900463789,
            0.9636104174099179]],

          [[0.8747756985388362, 0.8747756985388362, 0.8558062035375544,
            0.862086644450141]]]], dtype=object),
  array([[[[1.0, 1.0, 1.0, 1.0]],

          [[1.148333621136246, 1.148333621136246, 1.1194957692971854,
            1.1226040407528926]],

          [[0.7586206896551724, 0.7643516270033996, 0.7556095191840699,
            0.7639630888780962]],

          [[0.9733515544926545, 0.9871313062293589, 0.9708461450859811,
            0.9851953080514748]],

          [[0.9643239386371745, 0.966464502318944, 0.9611130931145202,
            0.9650374598644309]],

          [[0.8747756985388362, 0.8758010766470136, 0.8659318123558063,
            0.874647526275314]]]], dtype=object),
  array([[[[1.0, 1.0, 1.0, 1.0]],

          [[1.1411673286133655, 1.1535140735624245, 1.1325332412364013,
            1.1478155758936281]],


In [67]:
len(price_history),price_history

(504,
 [array([[1],
         [1],
         [1],
         [1],
         [1],
         [1]]),
  array([[1.        ],
         [1.00009412],
         [0.97985552],
         [1.0229703 ],
         [0.99950642],
         [0.99367186]]),
  array([[1.        ],
         [1.01402221],
         [1.00822345],
         [0.98848238],
         [1.06320988],
         [1.01335819]]),
  array([[1.        ],
         [1.03842227],
         [1.02545352],
         [1.02839518],
         [1.0013934 ],
         [1.01333538]]),
  array([[1.        ],
         [1.00107248],
         [0.98518925],
         [0.98086261],
         [0.98979592],
         [0.98517622]]),
  array([[1.        ],
         [0.97535934],
         [0.98997773],
         [0.98641041],
         [1.00093721],
         [0.99800399]]),
  array([[1.        ],
         [1.00887872],
         [0.99254781],
         [0.9916355 ],
         [0.99157303],
         [1.00292308]]),
  array([[1.        ],
         [0.99618944],
         [0.99150021],
         [0.98819093],
         [0.97733711],
         [0.98005829]]),
  array([[1.        ],
         [0.97285974],
         [1.00428633],
         [0.96716208],
         [1.01111111],
         [0.99045234]]),
  array([[1.        ],
         [0.99222992],
         [1.02048656],
         [1.00602222],
         [0.98757764],
         [1.00726928]]),
  array([[1.        ],
         [1.02575715],
         [0.99665412],
         [1.0325111 ],
         [1.00725689],
         [1.00737371]]),
  array([[1.        ],
         [1.00763429],
         [1.0006994 ],
         [1.03248701],
         [1.05235351],
         [1.00171313]]),
  array([[1.        ],
         [1.02601552],
         [1.0271177 ],
         [1.00687385],
         [1.01186673],
         [1.00124378]]),
  array([[1.        ],
         [1.00516014],
         [1.0078933 ],
         [0.99144231],
         [1.01939558],
         [1.00263975]]),
  array([[1.        ],
         [1.00106213],
         [0.98217661],
         [1.00853457],
         [1.0340708 ],
         [0.99318569]]),
  array([[1.        ],
         [0.96498674],
         [0.98240308],
         [0.98990288],
         [0.98673513],
         [0.97848121]]),
  array([[1.        ],
         [1.05653289],
         [0.98306745],
         [0.95638236],
         [1.01734605],
         [0.98151394]]),
  array([[1.        ],
         [1.03113347],
         [1.01978648],
         [0.91223972],
         [1.00468883],
         [1.00665692]]),
  array([[1.        ],
         [0.98536585],
         [0.97892239],
         [0.99187173],
         [0.98812049],
         [1.02790323]]),
  array([[1.        ],
         [1.01254694],
         [1.01397405],
         [1.01178716],
         [1.00171748],
         [1.00172603]]),
  array([[1.        ],
         [1.00016859],
         [1.0113908 ],
         [1.00532564],
         [1.0025718 ],
         [1.01738722]]),
  array([[1.        ],
         [1.00766962],
         [1.00500556],
         [0.99326785],
         [1.10902095],
         [1.0195535 ]]),
  array([[1.        ],
         [1.00317832],
         [1.01134477],
         [0.96666667],
         [1.03392444],
         [1.02612504]]),
  array([[1.        ],
         [0.99157912],
         [0.99233926],
         [0.98482759],
         [0.9906786 ],
         [0.98395879]]),
  array([[1.        ],
         [1.00664256],
         [0.99710505],
         [1.00373483],
         [0.96687994],
         [0.99252169]]),
  array([[1.        ],
         [1.01921149],
         [1.00594497],
         [1.01465116],
         [1.01440249],
         [0.99668475]]),
  array([[1.        ],
         [1.02343878],
         [1.00343595],
         [0.98556039],
         [1.00153492],
         [1.005443  ]]),
  array([[1.        ],
         [1.01265215],
         [1.02164087],
         [1.0127907 ],
         [1.03869732],
         [1.01849624]]),
  array([[1.        ],
         [1.00490274],
         [1.02574072],
         [1.02238806],
         [1.00700848],
         [0.99527536]]),
  array([[1.        ],
         [1.00590179],
         [1.00810352],
         [0.97529478],
         [0.97435897],
         [1.00459872]]),
  array([[1.        ],
         [1.00696237],
         [1.00777907],
         [0.99873345],
         [1.05338346],
         [0.99350266]]),
  array([[1.        ],
         [0.99790242],
         [1.        ],
         [1.00172931],
         [0.97680228],
         [1.        ]]),
  array([[1.        ],
         [1.00817439],
         [1.01054934],
         [0.9971228 ],
         [0.995981  ],
         [1.01441736]]),
  array([[1.        ],
         [1.02702703],
         [0.99427116],
         [0.98649584],
         [0.99156273],
         [1.        ]]),
  array([[1.        ],
         [0.9937594 ],
         [0.99462228],
         [0.99087399],
         [1.02626711],
         [0.99809524]]),
  array([[1.        ],
         [0.97442687],
         [1.0050206 ],
         [1.01771165],
         [0.99819755],
         [1.0019084 ]]),
  array([[1.        ],
         [1.01257862],
         [1.01140003],
         [0.99048614],
         [1.01589021],
         [1.00278388]]),
  array([[1.        ],
         [0.98504716],
         [1.00177305],
         [0.99707157],
         [1.00675435],
         [0.99108708]]),
  array([[1.        ],
         [1.00490425],
         [1.00872314],
         [0.98684211],
         [0.99258475],
         [1.02565237]]),
  array([[1.        ],
         [1.00209156],
         [0.98997368],
         [0.97119048],
         [0.99003913],
         [0.98936323]]),
  array([[1.        ],
         [0.9936611 ],
         [0.98278263],
         [1.04792841],
         [1.00215595],
         [0.99433387]]),
  array([[1.        ],
         [0.98342928],
         [1.0127528 ],
         [1.00713534],
         [1.00609537],
         [1.00131502]]),
  array([[1.        ],
         [1.00150305],
         [0.98639023],
         [0.98025552],
         [0.98039914],
         [0.98248942]]),
  array([[1.        ],
         [1.0042654 ],
         [1.00490006],
         [0.9778436 ],
         [0.9912759 ],
         [1.00787168]]),
  array([[1.        ],
         [0.97931414],
         [0.97523418],
         [1.00533139],
         [0.97433077],
         [0.97701149]]),
  array([[1.        ],
         [0.98176853],
         [1.00013158],
         [0.9881885 ],
         [1.01016184],
         [0.99834087]]),
  array([[1.        ],
         [1.01807919],
         [1.01828707],
         [0.99914624],
         [1.01080477],
         [1.01812963]]),
  array([[1.        ],
         [0.99308959],
         [1.00284238],
         [0.99926758],
         [0.97899005],
         [0.98323193]]),
  array([[1.        ],
         [1.01100413],
         [1.00914713],
         [1.02614219],
         [0.97213855],
         [1.01494114]]),
  array([[1.        ],
         [1.01672669],
         [1.01697945],
         [1.00595238],
         [1.03601859],
         [0.98319703]]),
  array([[1.        ],
         [1.0112563 ],
         [0.96522722],
         [1.00106509],
         [1.05084112],
         [1.01209921]]),
  array([[1.        ],
         [0.9924496 ],
         [1.0032514 ],
         [1.01359499],
         [0.99075062],
         [0.99835625]]),
  array([[1.        ],
         [0.98745098],
         [1.00285196],
         [0.99370189],
         [1.0021544 ],
         [1.00898069]]),
  array([[1.        ],
         [1.01040508],
         [0.98694416],
         [0.98884977],
         [0.99534217],
         [0.99510458]]),
  array([[1.        ],
         [0.99591227],
         [0.98821218],
         [0.99264095],
         [0.9924406 ],
         [1.00029815]]),
  array([[1.        ],
         [0.97387323],
         [0.96925116],
         [1.00143489],
         [0.96808125],
         [0.97958271]]),
  array([[1.        ],
         [1.00697034],
         [0.99781212],
         [1.00501493],
         [0.99437992],
         [0.99787007]]),
  array([[1.        ],
         [0.99203155],
         [1.00465945],
         [1.00487109],
         [1.00904295],
         [0.99923769]]),
  array([[1.        ],
         [1.0253144 ],
         [1.0039558 ],
         [0.99196027],
         [1.0115758 ],
         [1.00183094]]),
  array([[1.        ],
         [0.98464826],
         [1.00461957],
         [0.99213349],
         [0.98855666],
         [0.99619251]]),
  array([[1.        ],
         [0.9985534 ],
         [1.01528266],
         [0.98942816],
         [1.01792382],
         [0.99648372]]),
  array([[1.        ],
         [1.00861167],
         [1.00812575],
         [0.99902865],
         [1.02164343],
         [1.00168763]]),
  array([[1.        ],
         [1.01619853],
         [1.00726744],
         [0.99440933],
         [1.05385996],
         [0.99862153]]),
  array([[1.        ],
         [0.98947782],
         [0.99239145],
         [1.00476656],
         [0.98705281],
         [1.00920245]]),
  array([[1.        ],
         [0.99674629],
         [0.99722406],
         [1.03868143],
         [1.01898516],
         [1.0106383 ]]),
  array([[1.        ],
         [1.00764331],
         [1.01179745],
         [1.00878323],
         [1.01287263],
         [0.99909774]]),
  array([[1.        ],
         [1.00426675],
         [1.0026202 ],
         [0.98188995],
         [1.02207358],
         [0.99849488]]),
  array([[1.        ],
         [0.99803304],
         [0.99333595],
         [0.99645306],
         [0.99378272],
         [0.98899608]]),
  array([[1.        ],
         [0.99566417],
         [0.99907919],
         [1.00854295],
         [1.0250247 ],
         [0.99878067]]),
  array([[1.        ],
         [1.00380048],
         [1.00105332],
         [0.99611765],
         [1.01991648],
         [1.00228903]]),
  array([[1.        ],
         [0.99518852],
         [0.98842562],
         [0.99279556],
         [0.97889764],
         [0.99954324]]),
  array([[1.        ],
         [0.98874534],
         [0.97338656],
         [0.97430407],
         [0.96557272],
         [0.98278751]]),
  array([[1.        ],
         [1.02284569],
         [1.01052632],
         [1.003663  ],
         [1.01166278],
         [1.00309981]]),
  array([[1.        ],
         [0.99459248],
         [1.0094697 ],
         [1.0026764 ],
         [1.0171278 ],
         [1.00973424]]),
  array([[1.        ],
         [1.01347412],
         [1.01179308],
         [0.9955108 ],
         [1.04760363],
         [1.0407039 ]]),
  array([[1.        ],
         [1.00816358],
         [1.01350993],
         [1.00280317],
         [0.9496136 ],
         [0.99573592]]),
  array([[1.        ],
         [1.00470425],
         [1.00026137],
         [1.02783179],
         [1.02018229],
         [0.996456  ]]),
  array([[1.        ],
         [1.01819159],
         [1.00013065],
         [1.00390209],
         [0.99521378],
         [0.9943687 ]]),
  array([[1.        ],
         [0.98424425],
         [0.99307642],
         [1.00212014],
         [0.99422892],
         [0.99508197]]),
  array([[1.        ],
         [0.98529412],
         [1.00828729],
         [0.96908792],
         [0.99000322],
         [1.00853677]]),
  array([[1.        ],
         [0.97287002],
         [0.99230267],
         [0.98593087],
         [0.98469055],
         [0.98084348]]),
  array([[1.        ],
         [1.03036356],
         [1.00486458],
         [0.9985238 ],
         [1.02249421],
         [0.99576079]]),
  array([[1.        ],
         [0.99806126],
         [0.99241136],
         [0.9928545 ],
         [1.00776448],
         [0.99711114]]),
  array([[1.        ],
         [0.97746698],
         [0.98879367],
         [0.98697109],
         [0.97367576],
         [1.00579445]]),
  array([[1.        ],
         [0.99372019],
         [0.99306667],
         [1.00578325],
         [0.98780086],
         [0.9956034 ]]),
  array([[1.        ],
         [1.00199984],
         [1.00335661],
         [1.075     ],
         [1.01134846],
         [1.01385716]]),
  array([[1.        ],
         [1.01884081],
         [1.02114278],
         [1.01232558],
         [1.01122112],
         [1.04340643]]),
  array([[1.        ],
         [0.98981351],
         [1.00615909],
         [0.99609465],
         [1.00652742],
         [0.99352238]]),
  array([[1.        ],
         [0.99635845],
         [0.99726491],
         [1.00057657],
         [1.02172503],
         [0.99521878]]),
  array([[1.        ],
         [1.0011918 ],
         [1.00666057],
         [1.00875879],
         [1.01555062],
         [0.99941767]]),
  array([[1.        ],
         [1.02333148],
         [1.0304878 ],
         [1.00993945],
         [1.0059375 ],
         [1.01966497]]),
  array([[1.        ],
         [0.99860411],
         [0.99357925],
         [1.00067873],
         [1.01708605],
         [0.99385714]]),
  array([[1.        ],
         [1.01102741],
         [1.00620882],
         [0.98473887],
         [0.99114233],
         [1.00618083]]),
  array([[1.        ],
         [0.99907827],
         [1.0026445 ],
         [1.01262771],
         [1.00493066],
         [1.00228571]]),
  array([[1.        ],
         [0.99992312],
         [0.9998744 ],
         [1.02822809],
         [0.98650721],
         [0.99458381]]),
  array([[1.        ],
         [1.01022605],
         [1.01193317],
         [1.03506064],
         [0.98880945],
         [0.99412439]]),
  array([[1.        ],
         [1.00875257],
         [0.99354518],
         [0.99350234],
         [0.9971707 ],
         [1.00360386]]),
  array([[1.        ],
         [0.97796892],
         [0.99150425],
         [0.99195883],
         [0.99716267],
         [0.98448722]]),
  array([[1.        ],
         [1.01866996],
         [1.01008065],
         [1.00086468],
         [0.98766993],
         [1.01386052]]),
  array([[1.        ],
         [0.9980309 ],
         [0.99825349],
         [0.98218143],
         [0.99807939],
         [1.00100734]]),
  array([[1.        ],
         [0.98861739],
         [0.98837791],
         [0.98207806],
         [0.99166132],
         [0.98734905]]),
  array([[1.        ],
         [1.00191894],
         [1.00986218],
         [1.01634572],
         [0.99611902],
         [1.00626092]]),
  array([[1.        ],
         [0.99563319],
         [0.99937398],
         [0.99702578],
         [0.99155844],
         [0.99898712]]),
  array([[1.        ],
         [1.00123115],
         [1.00388374],
         [1.00309358],
         [0.99639817],
         [0.99869641]]),
  array([[1.        ],
         [0.99415924],
         [0.98277799],
         [0.99779711],
         [0.98652645],
         [0.98926759]]),
  array([[1.        ],
         [0.99451144],
         [1.00139683],
         [1.00132465],
         [1.00099933],
         [1.0023457 ]]),
  array([[1.        ],
         [0.99339293],
         [0.99112351],
         [0.97332157],
         [0.97404326],
         [0.98990785]]),
  array([[1.        ],
         [0.9970266 ],
         [0.99667349],
         [0.99195832],
         [0.99555859],
         [1.00398936]]),
  array([[1.        ],
         [1.01145817],
         [1.02130937],
         [1.01507193],
         [1.02882636],
         [1.02472406]]),
  array([[1.        ],
         [0.99774984],
         [1.00113122],
         [0.98098988],
         [1.01767845],
         [1.00014362]]),
  array([[1.        ],
         [0.98895715],
         [1.00263653],
         [0.99334939],
         [0.99770567],
         [0.99554854]]),
  array([[1.        ],
         [0.99803413],
         [0.98797896],
         [0.99411289],
         [1.00788436],
         [0.98903793]]),
  array([[1.        ],
         [1.00535771],
         [1.01318124],
         [0.99965165],
         [0.99217731],
         [1.0064168 ]]),
  array([[1.        ],
         [0.9976489 ],
         [0.97460595],
         [1.00824718],
         [0.98390276],
         [0.99623243]]),
  array([[1.        ],
         [1.00455617],
         [1.01899628],
         [0.99942396],
         [1.00801336],
         [1.01090909]]),
  array([[1.        ],
         [0.98999062],
         [1.00390477],
         [0.98835735],
         [0.98277575],
         [0.98834532]]),
  array([[1.        ],
         [1.00797788],
         [1.03237139],
         [0.99930021],
         [1.02797438],
         [1.00582326]]),
  array([[1.        ],
         [0.9954549 ],
         [1.0154351 ],
         [0.9929972 ],
         [1.01672131],
         [1.00477638]]),
  array([[1.        ],
         [1.00850193],
         [0.99820467],
         [1.00105783],
         [0.98387617],
         [0.99193316]]),
  array([[1.        ],
         [0.99523847],
         [1.00647482],
         [1.00082189],
         [1.02097673],
         [0.99651467]]),
  array([[1.        ],
         [0.99411765],
         [0.98570407],
         [0.9770061 ],
         [1.00064205],
         [1.00189449]]),
  array([[1.        ],
         [0.98248521],
         [0.98235436],
         [0.97346302],
         [0.97401347],
         [0.97047273]]),
  array([[1.        ],
         [1.00714687],
         [0.99667815],
         [1.01480202],
         [0.93511199],
         [1.00644484]]),
  array([[1.        ],
         [1.00940839],
         [0.99913591],
         [1.00230947],
         [1.00422684],
         [1.01042442]]),
  array([[1.        ],
         [0.99873618],
         [0.99765258],
         [0.99527043],
         [0.99579095],
         [1.00574797]]),
  array([[1.        ],
         [0.99652009],
         [0.99690402],
         [0.97758011],
         [0.98767172],
         [0.9982415 ]]),
  array([[1.        ],
         [0.99753968],
         [1.00111801],
         [0.99239686],
         [1.00463623],
         [0.99486201]]),
  array([[1.        ],
         [0.97517702],
         [0.99255491],
         [0.97889977],
         [0.95172169],
         [0.98465398]]),
  array([[1.        ],
         [0.97960349],
         [1.00600075],
         [1.01411342],
         [1.02051473],
         [1.00479544]]),
  array([[1.        ],
         [1.0267344 ],
         [1.00149124],
         [1.0159413 ],
         [1.0380117 ],
         [1.02043251]]),
  array([[1.        ],
         [1.01930565],
         [1.01054721],
         [1.01942715],
         [1.00950704],
         [1.01607717]]),
  array([[1.        ],
         [0.9996021 ],
         [1.00552554],
         [0.99560225],
         [0.98709452],
         [1.00834292]]),
  array([[1.        ],
         [1.00963299],
         [1.00280865],
         [0.99055215],
         [0.98657244],
         [0.99885877]]),
  array([[1.        ],
         [1.01332597],
         [1.00487092],
         [1.00990958],
         [1.002149  ],
         [1.0078549 ]]),
  array([[1.        ],
         [1.00863746],
         [0.99491032],
         [1.02244573],
         [1.00500357],
         [1.0043928 ]]),
  array([[1.        ],
         [1.0189014 ],
         [0.9998782 ],
         [0.99172265],
         [0.99964438],
         [1.0256772 ]]),
  array([[1.        ],
         [0.9900053 ],
         [0.98903642],
         [0.99842748],
         [1.01209534],
         [0.99064649]]),
  array([[1.        ],
         [0.95770554],
         [0.99433428],
         [1.01950569],
         [0.99753954],
         [0.99930575]]),
  array([[1.        ],
         [0.99952084],
         [0.99888517],
         [0.99679144],
         [1.02889359],
         [0.99694317]]),
  array([[1.        ],
         [0.99472675],
         [1.00421627],
         [0.98974726],
         [1.00239726],
         [1.04250871]]),
  array([[1.        ],
         [0.98610442],
         [0.98703384],
         [0.98048663],
         [0.98667578],
         [0.98743316]]),
  array([[1.        ],
         [1.00496864],
         [1.00825723],
         [0.98968059],
         [1.01246537],
         [1.01191443]]),
  array([[1.        ],
         [0.99683903],
         [0.99578111],
         [0.99627607],
         [1.01025992],
         [1.01699224]]),
  array([[1.        ],